site_name: MSUM Astronomy Research Guide
theme: readthedocs
# site_favicon: favicon.ico
repo_url: https://github.com/mwcraig/astro_research_setup
nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Install python': 'getting-started/install_python.md'
    - 'Install astronomy-specifc packages': 'getting-started/install-astro-stuff.md'
    - 'Using jupyter notebooks': 'getting-started/run-notebooks.md'
  - 'Image Calibration':
    - 'Reduce (calibrate) your images': 'calibration/reducer.md'
