site_name: MSUM Astronomy Research Guide
theme: readthedocs
# site_favicon: favicon.ico
repo_url: https://github.com/mwcraig/astro_research_setup
nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Install python': 'getting-started/install_python.md'
    - 'Get a development copy of stellarphot': 'getting-started/stellarphot-development-install.md'
    - 'Learn about conda environments': 'getting-started/environments-new.md'
    - 'Install astronomy-specific packages': 'getting-started/install-astro-stuff.md'
    - 'Using jupyter notebooks': 'getting-started/run-notebooks.md'
  - 'Image Calibration':
    - 'Settings for calibration CG16M': 'calibration/camera-apogee-alta-cg16m.md'
    - 'Reduce (calibrate) your images': 'calibration/reducer.md'
